### ISSUE TITLE
The repo should have a readme

### ISSUE THREAD

**Issue by stof** [symfony-tools/docs-builder#87]

**Comment by OskarStark** [comment]
Do we plan to move this repo over to the symfony/ org or will it stay in your scope @weaverryan ?

**Comment by weaverryan** [comment]
No specific plans right now. Until recently, this was not used by anyone/anything except for the CI on symfony-docs. I am open to anything.

README would be good... but I'm not sure that we should, at this time, promote this library in any way. Or, at the very least, it would be a "use this at your own risk, we don't guarantee BC" because I think this should be a tool for the Symfony docs firstly.

**Comment by stof** [comment]
I'm fine with saying that this package is used at your own risk. The readme would still help knowing what this repo is (and could tell about the fact that no BC is guaranteed)

**Comment by javiereguiluz** [comment]
It's not only about "use at your own risk" ... but this is a 100% internal tool for Symfony. It's used in Symfony Docs public repository at GitHub and, soon, at symfony.com.

But this is not a generic doc build tool, it's only designed to build Symfony documentation.

**Comment by wouterj** [comment]
Thanks to Javier, the repo now has a repo :)
